steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--build-arg', 'VITE_WEATHER_API_KEY=${_VITE_WEATHER_API_KEY}', 
      '-t', 'us-central1-docker.pkg.dev/${_GCP_PROJECT_ID}/personal-project-repo/personal-project:latest', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_GCP_PROJECT_ID}/personal-project-repo/personal-project:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    if: '${_DEPLOY} == "true"'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'personal-project',
      '--image', 'us-central1-docker.pkg.dev/${_GCP_PROJECT_ID}/personal-project-repo/personal-project:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--service-account', '989496242585-compute@developer.gserviceaccount.com',
      '--quiet'
    ]

substitutions:
  _GCP_PROJECT_ID: 'rtruong-project'
  _VITE_WEATHER_API_KEY: ''
  _DEPLOY: 'true'  

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
