export const ABOUT_ME = () => {
    return (
        <>
            <p className='text-lg text-gray-600 leading-relaxed'>
                Hi, I’m <span className="font-semibold text-blue-600">Ryan Truong</span>. I am a <span className="font-semibold text-blue-600">Software Engineer</span> at <span className="font-semibold text-blue-600">HCA Healthcare</span> on the <span className="italic text-blue-600">HR Transformation and Analytics</span> team, where I focus on <span className="font-semibold text-blue-600">Advanced Analytics</span> and <span className="font-semibold text-blue-600">Innovation</span>. I earned my <span className="font-semibold text-blue-600">B.S. in Computer Science and Economics</span> from <span className="font-semibold text-blue-600">Belmont University</span>, where I built a strong foundation in technical and analytical problem-solving. At Belmont, I worked on projects such as building <span className="font-semibold text-blue-600">full stack applications</span> with <span className="text-blue-600">Python</span> and <span className="text-blue-600">React</span>, designing small <span className="text-blue-600">ETL pipelines</span>, and applying <span className="text-blue-600">machine learning models</span> to real world datasets. That combination of engineering and analysis continues to shape how I approach designing <span className="font-semibold text-blue-600">practical</span> and <span className="font-semibold text-blue-600">reliable AI systems</span> at work today. On the technical side, I work primarily with <span className="text-blue-600">Python</span>, <span className="text-blue-600">TypeScript</span>, <span className="text-blue-600">Node</span>, <span className="text-blue-600">React</span>, <span className="text-blue-600">Flask</span>, and <span className="text-blue-600">GCP</span>, with a focus on <span className="text-blue-600">machine learning</span> and <span className="text-blue-600">artificial intelligence</span>. Outside of work I enjoy <span className="italic text-blue-600">running</span>, <span className="italic text-blue-600">gaming</span>, and <span className="italic text-blue-600">cooking</span>. I am currently training with the goal of qualifying for the <span className="font-semibold text-blue-600">Boston Marathon</span> while making the most of the opportunities in front of me. Thank you for visiting my site. I look forward to connecting with you.
            </p>
        </>
    );
};
