name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config=cloudbuild.yaml \
          --substitutions=_GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
 