name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Create Cloud Build Config
      run: |
        echo "steps:
        - name: 'gcr.io/cloud-builders/docker'
          args: ['build', '--build-arg', 'VITE_WEATHER_API_KEY=$_VITE_WEATHER_API_KEY', '-t', 'us-central1-docker.pkg.dev/$_GCP_PROJECT_ID/personal-project-repo/personal-project:latest', '.']
        - name: 'gcr.io/cloud-builders/docker'
          args: ['push', 'us-central1-docker.pkg.dev/$_GCP_PROJECT_ID/personal-project-repo/personal-project:latest']
        images:
        - 'us-central1-docker.pkg.dev/$_GCP_PROJECT_ID/personal-project-repo/personal-project:latest'
        options:
          logging: CLOUD_LOGGING_ONLY" > cloudbuild_tmp.yaml

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config=cloudbuild_tmp.yaml \
          --substitutions=_VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }},_GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --service-account=989496242585-compute@developer.gserviceaccount.com

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy personal-project \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-project-repo/personal-project:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account=989496242585-compute@developer.gserviceaccount.com