name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build the Docker image
      env:
        VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
      run: |
        docker build --build-arg VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }} \
        -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-project-repo/personal-project:latest .

    - name: Push the Docker image
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-project-repo/personal-project:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy personal-project \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-project-repo/personal-project:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account=989496242585-compute@developer.gserviceaccount.com

    - name: Create Cloud Build Configuration File
      run: |
        echo "steps:
        - name: 'gcr.io/cloud-builders/docker'
          id: Build
          args: ['build', '--build-arg', 'VITE_WEATHER_API_KEY=\$_VITE_WEATHER_API_KEY', '-t', 'us-central1-docker.pkg.dev/\$_GCP_PROJECT_ID/personal-project-repo/personal-project:latest', '.']
        - name: 'gcr.io/cloud-builders/docker'
          id: Push
          args: ['push', 'us-central1-docker.pkg.dev/\$_GCP_PROJECT_ID/personal-project-repo/personal-project:latest']
        - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
          id: Deploy
          args: ['gcloud', 'run', 'deploy', 'personal-project', '--image', 'us-central1-docker.pkg.dev/\$_GCP_PROJECT_ID/personal-project-repo/personal-project:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--service-account', '989496242585-compute@developer.gserviceaccount.com']
        options:
          logging: CLOUD_LOGGING_ONLY" > cloudbuild.yaml

    - name: Submit Build with Cloud Build Configuration
      run: |
        gcloud builds submit \
          --config=cloudbuild.yaml \
          --substitutions=_VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }},_GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}