name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure docker for gcloud
      run: gcloud auth configure-docker

    - name: Build the Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/personal-project .

    - name: Push the Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/personal-project

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy personal-project \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/personal-project \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated